import {
  Combine,
  SplitSquareVertical,
  FileArchive,
  Image,
  FileImage,
  RotateCw,
  Stamp,
  PenTool,
  Lock,
  Trash2,
  ListOrdered,
  Images,
  FileText,
  ScanText,
  LayoutGrid,
} from 'lucide-react';

export const tools = [
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    slug: '/merge-pdf',
    description: 'Combine multiple PDF files into a single unified document in any order you choose.',
    icon: Combine,
    color: 'text-blue-600',
    bgColor: 'bg-blue-50',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    slug: '/split-pdf',
    description: 'Separate one or more pages from a PDF file or split every page into individual files.',
    icon: SplitSquareVertical,
    color: 'text-orange-600',
    bgColor: 'bg-orange-50',
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    slug: '/remove-pages',
    description: 'Delete selected pages from your PDF file and save a clean, shortened document.',
    icon: Trash2,
    color: 'text-red-600',
    bgColor: 'bg-red-50',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    slug: '/compress-pdf',
    description: 'Reduce file size and optimize PDF data structures without degrading visual quality.',
    icon: FileArchive,
    color: 'text-green-600',
    bgColor: 'bg-green-50',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    slug: '/jpg-to-pdf',
    description: 'Transform JPG images into high-resolution, shareable PDF documents instantly.',
    icon: Image,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-50',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    slug: '/pdf-to-jpg',
    description: 'Extract every page of a PDF document and convert it into high-definition JPG images.',
    icon: FileImage,
    color: 'text-purple-600',
    bgColor: 'bg-purple-50',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    slug: '/rotate-pdf',
    description: 'Permanently rotate PDF pages 90, 180, or 270 degrees clockwise or counterclockwise.',
    icon: RotateCw,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
  },
  {
    id: 'watermark-pdf',
    name: 'Add Watermark',
    slug: '/watermark-pdf',
    description: 'Stamp custom text watermarks onto PDF pages with configurable opacity, size, and angles.',
    icon: Stamp,
    color: 'text-teal-600',
    bgColor: 'bg-teal-50',
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    slug: '/sign-pdf',
    description: 'Draw or place your handwritten digital signature directly onto any PDF document.',
    icon: PenTool,
    color: 'text-pink-600',
    bgColor: 'bg-pink-50',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    slug: '/protect-pdf',
    description: 'Encrypt your PDF documents with custom master passwords directly inside your browser.',
    icon: Lock,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50',
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    slug: '/organize-pdf',
    description: 'Reorder, rotate and delete PDF pages visually with drag and drop thumbnails.',
    icon: LayoutGrid,
    color: 'text-amber-600',
    bgColor: 'bg-amber-50',
  },
  {
    id: 'add-page-numbers',
    name: 'Add Page Numbers',
    slug: '/add-page-numbers',
    description: 'Number your PDF pages with custom position, format, font size and starting number.',
    icon: ListOrdered,
    color: 'text-sky-600',
    bgColor: 'bg-sky-50',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    slug: '/image-to-pdf',
    description: 'Combine JPG, PNG and WebP images into one PDF with A4, Letter or fit-to-image pages.',
    icon: Images,
    color: 'text-lime-600',
    bgColor: 'bg-lime-50',
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    slug: '/pdf-to-text',
    description: 'Extract all the text from a PDF instantly, then copy it or download it as a TXT file.',
    icon: FileText,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF & Image',
    slug: '/ocr-pdf',
    description: 'Recognise text in scanned PDFs and images in Arabic, French, English and more.',
    icon: ScanText,
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-50',
  },
];