import { 
  Combine, 
  SplitSquareHorizontal, 
  FileMinus, 
  Minimize2, 
  Image as ImageIcon, 
  FileImage, 
  RotateCw, 
  Stamp, 
  PenTool, 
  Lock, 
  LayoutGrid, 
  ListOrdered, 
  FileUp, 
  FileText, 
  ScanText,
  FileCode2
} from 'lucide-react';

export const tools = [
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into a single unified document in any order you choose.',
    icon: Combine,
    color: 'text-blue-600',
    bg: 'bg-blue-50',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate one or more pages from a PDF file or split every page into individual files.',
    icon: SplitSquareHorizontal,
    color: 'text-orange-600',
    bg: 'bg-orange-50',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size and optimize PDF data structures without degrading visual quality.',
    icon: Minimize2,
    color: 'text-emerald-600',
    bg: 'bg-emerald-50',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Transform JPG images into high-resolution, shareable PDF documents instantly.',
    icon: ImageIcon,
    color: 'text-yellow-600',
    bg: 'bg-yellow-50',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Extract every page of a PDF document and convert it into high-definition JPG images.',
    icon: FileImage,
    color: 'text-purple-600',
    bg: 'bg-purple-50',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Permanently rotate PDF pages 90, 180, or 270 degrees clockwise or counterclockwise.',
    icon: RotateCw,
    color: 'text-indigo-600',
    bg: 'bg-indigo-50',
  },
  {
    id: 'watermark-pdf',
    name: 'Add Watermark',
    description: 'Stamp custom text watermarks onto PDF pages with configurable opacity, size, and angles.',
    icon: Stamp,
    color: 'text-teal-600',
    bg: 'bg-teal-50',
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Draw or place your handwritten digital signature directly onto any PDF document.',
    icon: PenTool,
    color: 'text-pink-600',
    bg: 'bg-pink-50',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt your PDF documents with custom master passwords directly inside your browser.',
    icon: Lock,
    color: 'text-green-600',
    bg: 'bg-green-50',
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Reorder, rotate and delete PDF pages visually with drag and drop thumbnails.',
    icon: LayoutGrid,
    color: 'text-orange-500',
    bg: 'bg-orange-50',
  },
  {
    id: 'add-page-numbers',
    name: 'Add Page Numbers',
    description: 'Number your PDF pages with custom position, format, font size and starting number.',
    icon: ListOrdered,
    color: 'text-blue-500',
    bg: 'bg-blue-50',
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    description: 'Delete selected pages from your PDF file and save a clean, shortened document.',
    icon: FileMinus,
    color: 'text-red-600',
    bg: 'bg-red-50',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert various image formats into a single PDF document.',
    icon: FileUp,
    color: 'text-green-500',
    bg: 'bg-green-50',
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Extract raw text from PDF files directly in your browser.',
    icon: FileText,
    color: 'text-blue-700',
    bg: 'bg-blue-50',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF & Image',
    description: 'Extract text from scanned PDFs and images.',
    icon: ScanText,
    color: 'text-fuchsia-600',
    bg: 'bg-fuchsia-50',
  },
  {
    id: 'pdf-to-md',
    name: 'PDF to MD',
    description: 'Extract formatted text locally for Notion or Obsidian.',
    icon: FileCode2,
    color: 'text-indigo-600',
    bg: 'bg-indigo-50',
  }
];